# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KernelDist_single <- function(X, A, diag, bw, bw_A) {
    .Call(`_proximalDTR_KernelDist_single`, X, A, diag, bw, bw_A)
}

EpanKernelDist_single <- function(X, diag) {
    .Call(`_proximalDTR_EpanKernelDist_single`, X, diag)
}

Basis_func <- function(X_tmp, A_tmp, A_type, node1, node2, node3, node4, node5, node6) {
    .Call(`_proximalDTR_Basis_func`, X_tmp, A_tmp, A_type, node1, node2, node3, node4, node5, node6)
}

V_func <- function(X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6) {
    .Call(`_proximalDTR_V_func`, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6)
}

V_grad <- function(X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6, X_size) {
    .Call(`_proximalDTR_V_grad`, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6, X_size)
}

Pi_policy <- function(A_tmp, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6) {
    .Call(`_proximalDTR_Pi_policy`, A_tmp, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6)
}

Pi_grad <- function(A_tmp, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6, X_size) {
    .Call(`_proximalDTR_Pi_grad`, A_tmp, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6, X_size)
}

mu <- function(A_tmp, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6) {
    .Call(`_proximalDTR_mu`, A_tmp, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6)
}

mu_grad_beta <- function(A_tmp, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6, X_size) {
    .Call(`_proximalDTR_mu_grad_beta`, A_tmp, X_tmp, A_type, beta, lambda, node1, node2, node3, node4, node5, node6, X_size)
}

lagr_lambda <- function(X_tmp, lambda, omega) {
    .Call(`_proximalDTR_lagr_lambda`, X_tmp, lambda, omega)
}

lagr_lambda_grad <- function(X_tmp, lambda, omega) {
    .Call(`_proximalDTR_lagr_lambda_grad`, X_tmp, lambda, omega)
}

loss_grad <- function(train, beta, omega, A_type, eta_b, eta_omg, gamma, lambda, kernel_mat, node1, node2, node3, node4, node5, node6, X_size) {
    .Call(`_proximalDTR_loss_grad`, train, beta, omega, A_type, eta_b, eta_omg, gamma, lambda, kernel_mat, node1, node2, node3, node4, node5, node6, X_size)
}

kernel_obj <- function(train, beta, omega, A_type, gamma, lambda, kernel_mat, node1, node2, node3, node4, node5, node6, X_size) {
    .Call(`_proximalDTR_kernel_obj`, train, beta, omega, A_type, gamma, lambda, kernel_mat, node1, node2, node3, node4, node5, node6, X_size)
}

